blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Ask a question or discuss of the PKWK Update Notifier.
    url: https://github.com/Awayume/pkwk-update-notifier/discussions
